## Importing Data with Pandas

### Introduction

Working with data provided by the Python packages is a great way to learn the tools of data science, but at some point you want to stop learning and start working with your own data. In this chapter, you will learn how to read plain-text rectangular files into Python. Here, we will only scratch the surface of data import, but many of the principles will translate to other forms of data. We will finish with a few pointers to packages that are useful for other types of data.

Importing data is one of the most essential and very first steps in any data related problem. The ability to import the data correctly is a must have skill for every aspiring data scientist. 

Data exists in many different forms, and not only should you know how to import various data formats but also how to analyze and manipulate the data to gain useful insights.

`pandas` is an open source Python library which is easy-to-use, provides high performance, and a data analysis tool for various data formats.

It gives you the capability to read various types of data formats like CSV, JSON, Excel, Pickle etc. It allows you to represent your data in a row and column tabular fashion, which makes the data readable and presentable.

`pandas` represent the data in a DataFrame form and provide you with extensive usage for data analysis and data manipulation. Once you start making sense out of the data using the various functionalities in pandas, you can then use this data for analyzing, forecasting, classifying, and more.

`pandas` has an input and output API which has a set of top-level `reader` and `writer` functions. The reader function is accessed with `pandas.read_json()` that returns a pandas object, and writer function is accessed with `pandas.to_json()` which is an object method.

To get other types of data into Python, keep following the `pd.read_` syntax.

### Prerequisites

We will learn how to load flat files in Python with the `pandas` package.

In [1]:
import pandas as pd

In [2]:
!curl https://raw.githubusercontent.com/hadley/r4ds/master/data/heights.csv >> heights.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53636  100 53636    0     0   125k      0 --:--:-- --:--:-- --:--:--  125k

### Getting Started

Most of `pandas.read_` functions are concerned with turning files into dataframes. These functions all have similar syntax: once you have mastered one, you can use others with ease. For the rest of this chapter, we will focus on `pandas.read_csv`. Not only are csv files one of the most common forms of data storage, but once you understand `pandas.read_csv()`, you can easily apply your knowledge to all the other functions

* `pd.read_csv()` reads comma delimited files, by changing the `sep` argument it also reads semicolon separated files (common in countries where , is used as the decimal place), reads tab delimited files, and reads in files with any delimiter.

The first argument to read_csv() is the most important: it's the path to the file to read.

In [7]:
!head heights.csv

"earn","height","sex","ed","age","race"
50000,74.4244387818035,"male",16,45,"white"
60000,65.5375428255647,"female",16,58,"white"
30000,63.6291977374349,"female",16,29,"white"
50000,63.1085616752971,"female",16,91,"other"
51000,63.4024835710879,"female",17,39,"white"
9000,64.3995075440034,"female",15,26,"white"
29000,61.6563258264214,"female",12,49,"white"
32000,72.6985437364783,"male",17,46,"white"
2000,72.0394668497611,"male",15,21,"hispanic"

In [8]:
df = pd.read_csv('heights.csv')

In [9]:
df.head()

      earn     height     sex  ed  age   race
0  50000.0  74.424439    male  16   45  white
1  60000.0  65.537543  female  16   58  white
2  30000.0  63.629198  female  16   29  white
3  50000.0  63.108562  female  16   91  other
4  51000.0  63.402484  female  17   39  white

In [5]:
df

         earn     height     sex  ed  age   race
0     50000.0  74.424439    male  16   45  white
1     60000.0  65.537543  female  16   58  white
2     30000.0  63.629198  female  16   29  white
3     50000.0  63.108562  female  16   91  other
4     51000.0  63.402484  female  17   39  white
...       ...        ...     ...  ..  ...    ...
1187  19000.0  72.165733    male  12   29  white
1188  15000.0  61.135800  female  18   82  white
1189   8000.0  63.664164  female  12   33  white
1190  60000.0  71.925836    male  12   50  white
1191   6000.0  68.368486    male  12   27  white

[1192 rows x 6 columns]

`read_csv()` uses the first line of the data for the column names, which is a very common convention. There are two cases where you might want to tweak this behavior:

1. Sometimes there are a few lines of metadata at the top of the file. You can use `skiprows=n` to skip the first `n` lines; or use `comment="#"` to drop all lines that start with (e.g.)

2. The data might not have column names. You can use `header=None` to tell `read_csv()` not to treat the first row as headings, and instead label them sequentially from 0 to n:

In [12]:
pd.read_csv('heights.csv', header=None)

          0                 1       2   3    4      5
0      earn            height     sex  ed  age   race
1     50000  74.4244387818035    male  16   45  white
2     60000  65.5375428255647  female  16   58  white
3     30000  63.6291977374349  female  16   29  white
4     50000  63.1085616752971  female  16   91  other
...     ...               ...     ...  ..  ...    ...
1188  19000  72.1657330563758    male  12   29  white
1189  15000  61.1357995311264  female  18   82  white
1190   8000  63.6641635315027  female  12   33  white
1191  60000  71.9258358024526    male  12   50  white
1192   6000  68.3684862144291    male  12   27  white

[1193 rows x 6 columns]

In [15]:
df.to_json('height.json')

In [16]:
df.to_excel('heights.xlsx')

In [17]:
df2 = pd.read_excel("heights.xlsx")

In [18]:
df.head()

      earn     height     sex  ed  age   race
0  50000.0  74.424439    male  16   45  white
1  60000.0  65.537543  female  16   58  white
2  30000.0  63.629198  female  16   29  white
3  50000.0  63.108562  female  16   91  other
4  51000.0  63.402484  female  17   39  white

In [19]:
df2.head()

   Unnamed: 0   earn     height     sex  ed  age   race
0           0  50000  74.424439    male  16   45  white
1           1  60000  65.537543  female  16   58  white
2           2  30000  63.629198  female  16   29  white
3           3  50000  63.108562  female  16   91  other
4           4  51000  63.402484  female  17   39  white

In [20]:
df.to_excel('heights_with_index.xlsx', index=False)

In [21]:
df3 = pd.read_excel('heights_with_index.xlsx')
df3.head()

    earn     height     sex  ed  age   race
0  50000  74.424439    male  16   45  white
1  60000  65.537543  female  16   58  white
2  30000  63.629198  female  16   29  white
3  50000  63.108562  female  16   91  other
4  51000  63.402484  female  17   39  white

In [22]:
temp_df = pd.read_html("https://www.fdic.gov/bank-failures/failed-bank-list")

In [23]:
temp_df

[                                            Bank Name                City  \
 0             Community Bank and Trust - West Georgia            LaGrange
 1                   Metropolitan Capital Bank & Trust             Chicago
 2                        The Santa Anna National Bank          Santa Anna
 3                                Pulaski Savings Bank             Chicago
 4                  The First National Bank of Lindsay             Lindsay
 5               Republic First Bank dba Republic Bank        Philadelphia
 6                                       Citizens Bank            Sac City
 7                            Heartland Tri-State Bank             Elkhart
 8                                 First Republic Bank       San Francisco
 9                                      Signature Bank            New York
 10                                Silicon Valley Bank         Santa Clara
 11                                  Almena State Bank              Almena
 12                         First City Bank of Florida   Fort Walton Beach
 13                               The First State Bank       Barboursville
 14                                 Ericson State Bank             Ericson
 15                   City National Bank of New Jersey              Newark
 16                                      Resolute Bank              Maumee
 17                              Louisa Community Bank              Louisa
 18                               The Enloe State Bank              Cooper
 19                Washington Federal Bank for Savings             Chicago
 20    The Farmers and Merchants State Bank of Argonia             Argonia
 21                                Fayette County Bank          Saint Elmo
 22  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 23                                     First NBC Bank         New Orleans
 24                                      Proficio Bank  Cottonwood Heights

             State   Cert                Acquiring Institution  \
 0         Georgia  25796                          Anchor Bank
 1        Illinois  57488              First Independence Bank
 2           Texas   5520            Coleman County State Bank
 3        Illinois  28611                      Millennium Bank
 4        Oklahoma   4134               First Bank & Trust Co.
 5    Pennsylvania  27332    Fulton Bank, National Association
 6            Iowa   8758            Iowa Trust & Savings Bank
 7          Kansas  25851               Dream First Bank, N.A.
 8      California  59017            JPMorgan Chase Bank, N.A.
 9        New York  57053                  Flagstar Bank, N.A.
 10     California  24735  First–Citizens Bank & Trust Company
 11         Kansas  15426                          Equity Bank
 12        Florida  16748            United Fidelity Bank, fsb
 13  West Virginia  14361                       MVB Bank, Inc.
 14       Nebraska  18265           Farmers and Merchants Bank
 15     New Jersey  21111                      Industrial Bank
 16           Ohio  58317                   Buckeye State Bank
 17       Kentucky  58112    Kentucky Farmers Bank Corporation
 18          Texas  10716                   Legend Bank, N. A.
 19       Illinois  30570                   Royal Savings Bank
 20         Kansas  17719                          Conway Bank
 21       Illinois   1802            United Fidelity Bank, fsb
 22      Wisconsin  30003  First-Citizens Bank & Trust Company
 23      Louisiana  58302                         Whitney Bank
 24           Utah  35495                    Cache Valley Bank

          Closing Date  Fund  Sort ascending
 0         May 1, 2026                 10551
 1    January 30, 2026                 10550
 2       June 27, 2025                 10549
 3    January 17, 2025                 10548
 4    October 18, 2024                 10547
 5      April 26, 2024                 10546
 6    November 3, 2023                 10545
 7       July 28, 2023                 10544
 8         May 1, 2023                 10543
 9      March 12, 2023                 10540
 10     March 10, 2023                 10539
 11   October 23, 2020                 10538
 12   October 16, 2020                 10537
 13      April 3, 2020                 10536
 14  February 14, 2020                 10535
 15   November 1, 2019                 10534
 16   October 25, 2019                 10533
 17   October 25, 2019                 10532
 18       May 31, 2019                 10531
 19  December 15, 2017                 10530
 20   October 13, 2017                 10529
 21       May 26, 2017                 10528
 22        May 5, 2017                 10527
 23     April 28, 2017                 10526
 24      March 3, 2017                 10525  ]

In [24]:
type(temp_df)

list

In [27]:
banks = temp_df[0]

In [28]:
banks.head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547

In [29]:
banks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bank Name              25 non-null     object
 1   City                   25 non-null     object
 2   State                  25 non-null     object
 3   Cert                   25 non-null     int64
 4   Acquiring Institution  25 non-null     object
 5   Closing Date           25 non-null     object
 6   Fund  Sort ascending   25 non-null     int64
dtypes: int64(2), object(5)
memory usage: 1.5+ KB

In [32]:
pd.read_csv('https://www.fdic.gov/bank-failures/download-data.csv', encoding='latin-1')

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund
0,Community Bank and Trust - West Georgia,LaGrange,GA,25796,Anchor Bank,1-May-26,10551
1,Metropolitan Capital Bank & Trust,Chicago,IL,57488,First Independence Bank,30-Jan-26,10550
2,The Santa Anna National Bank,Santa Anna,TX,5520,Coleman County State Bank,27-Jun-25,10549
3,Pulaski Savings Bank,Chicago,IL,28611,Millennium Bank,17-Jan-25,10548
4,The First National Bank of Lindsay,Lindsay,OK,4134,First Bank & Trust Co.,18-Oct-24,10547
...,...,...,...,...,...,...,...
569,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,6004
570,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,4648
571,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,4647
572,The National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,4646
573,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,4645