## Introduction to Pandas

* Pandas is an open source library built on top of NumPy
* Allows fast analysis, cleaning and preparation of data
* High performance and productivity
* Built-in visualization capability
* Work with data from many sources

### Overview of Pandas Capabilities

* Series
* DataFrames
* Selection
* Missing Data
* Operations
* Merging, Joining and Concatenating
* GroupBy
* Reshaping Data and Pivot Tables
* Time Series
* Data Input/Output

#### Pandas

This is a basic introduction to the pandas module.

First we start off with the customary imports.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

#### Object Creation

#### Series

* Similar to NumPy array
    * Built on top of it
* Can have axis labels

#### Series Creation

* Here we will show a few ways to create series
    * Throughout the course we will be primarily dealing with DataFrames
    * DataFrames will be discussed shortly
* Series can hold a variety of object types
* Numbers, strings etc

Create a series by passing a list, letting pandas create a default index value.

In [2]:
s = pd.Series([1,2,3,np.nan,4,5])

In [4]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [11]:
s[4]

np.float64(4.0)

#### Series

* Key to using a series is understanding its index
    * Pandas makes use of these index names/numbers
    * Allows fast lookups of information
    * Works like a hash table or dictionary

#### Series Examples

In [5]:
s_1 = pd.Series([1,2,3,4],
               ['USA', 'Germany', 'China', 'Japan'])

In [6]:
s_1

USA        1
Germany    2
China      3
Japan      4
dtype: int64

In [7]:
s_2 = pd.Series([1,2,5,6],
               ['USA', 'Germany', 'Italy', 'China'])

In [8]:
s_2

USA        1
Germany    2
Italy      5
China      6
dtype: int64

In [9]:
s_2['China'] # Indexing is type dependent

np.int64(6)

In [10]:
s_2.index

Index(['USA', 'Germany', 'Italy', 'China'], dtype='object')

In [12]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [13]:
s_1.index

Index(['USA', 'Germany', 'China', 'Japan'], dtype='object')

In [14]:
labels = ['a', 'b', 'c']
s_3 = pd.Series(data=labels)

In [15]:
s_3

0    a
1    b
2    c
dtype: object

In [16]:
s_3[2]

'c'

#### Series

* Matches operation off of the index
* Creates NaN object where missing matches
* Integers convert to floats

In [17]:
s_1

USA        1
Germany    2
China      3
Japan      4
dtype: int64

In [18]:
s_2

USA        1
Germany    2
Italy      5
China      6
dtype: int64

In [19]:
s_1 + s_2

China      9.0
Germany    4.0
Italy      NaN
Japan      NaN
USA        2.0
dtype: float64

### DataFrame Creation

Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns.

In [24]:
dates = pd.date_range('20260101', periods=10)

In [25]:
dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10'],
              dtype='datetime64[ns]', freq='D')

In [26]:
df = pd.DataFrame(np.random.randn(10,4),
                 index=dates,
                 columns=list('ABCD'))

In [27]:
df

                   A         B         C         D
2026-01-01  0.738467  0.171368 -0.115648 -0.301104
2026-01-02 -1.478522 -0.719844 -0.460639  1.057122
2026-01-03  0.343618 -1.763040  0.324084 -0.385082
2026-01-04 -0.676922  0.611676  1.031000  0.931280
2026-01-05 -0.839218 -0.309212  0.331263  0.975545
2026-01-06 -0.479174 -0.185659 -1.106335 -1.196207
2026-01-07  0.812526  1.356240 -0.072010  1.003533
2026-01-08  0.361636 -0.645120  0.361396  1.538037
2026-01-09 -0.035826  1.564644 -2.619745  0.821903
2026-01-10  0.087047 -0.299007  0.091761 -1.987569

Creating a DataFrame by passing a dictionary that can be converted to a series:

In [28]:
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20260101'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(['test', 'train', 'test', 'train']),
    'F': 'foo'
})

In [29]:
df2

     A          B    C  D      E    F
0  1.0 2026-01-01  1.0  3   test  foo
1  1.0 2026-01-01  1.0  3  train  foo
2  1.0 2026-01-01  1.0  3   test  foo
3  1.0 2026-01-01  1.0  3  train  foo

The columns of the DataFrame have different `dtypes`.

In [30]:
df2.info()  # VERY IMPORTANT

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      datetime64[s]
 2   C       4 non-null      float32
 3   D       4 non-null      int32
 4   E       4 non-null      category
 5   F       4 non-null      object
dtypes: category(1), datetime64[s](1), float32(1), float64(1), int32(1), object(1)
memory usage: 288.0+ bytes

#### Viewing Data

Here is how to view the top and bottom rows of the frame:

In [31]:
df.head()

                   A         B         C         D
2026-01-01  0.738467  0.171368 -0.115648 -0.301104
2026-01-02 -1.478522 -0.719844 -0.460639  1.057122
2026-01-03  0.343618 -1.763040  0.324084 -0.385082
2026-01-04 -0.676922  0.611676  1.031000  0.931280
2026-01-05 -0.839218 -0.309212  0.331263  0.975545

In [32]:
df.tail(2)

                   A         B         C         D
2026-01-09 -0.035826  1.564644 -2.619745  0.821903
2026-01-10  0.087047 -0.299007  0.091761 -1.987569

Display the index, columns:

In [33]:
df.index

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10'],
              dtype='datetime64[ns]', freq='D')

In [34]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [35]:
df.shape # (Row, Column)

(10, 4)

We can convert our DataFrame (of floating points) to a NumPy array.

In [39]:
#df.to_numpy()  # This can be a taxing operation in not all floats
df.values

array([[ 0.73846658,  0.17136828, -0.11564828, -0.3011037 ],
       [-1.47852199, -0.71984421, -0.46063877,  1.05712223],
       [ 0.34361829, -1.76304016,  0.32408397, -0.38508228],
       [-0.676922  ,  0.61167629,  1.03099952,  0.93128012],
       [-0.83921752, -0.30921238,  0.33126343,  0.97554513],
       [-0.47917424, -0.18565898, -1.10633497, -1.19620662],
       [ 0.81252582,  1.35624003, -0.07201012,  1.0035329 ],
       [ 0.36163603, -0.64511975,  0.36139561,  1.53803657],
       [-0.03582604,  1.56464366, -2.6197451 ,  0.8219025 ],
       [ 0.08704707, -0.29900735,  0.09176078, -1.98756891]])

In [40]:
df2.to_numpy() # This has multiple types

array([[1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

`describe()` shows a quick statistic summary of our data:

In [38]:
df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.116637  -0.021795  -0.223487   0.245746
std     0.738267   0.997130   1.012976   1.154750
min    -1.478522  -1.763040  -2.619745  -1.987569
25%    -0.627485  -0.561143  -0.374391  -0.364088
50%     0.025611  -0.242333   0.009875   0.876591
75%     0.357132   0.501599   0.329469   0.996536
max     0.812526   1.564644   1.031000   1.538037

Transposing your data:

In [41]:
df.T

,2026-01-01,2026-01-02,2026-01-03,2026-01-04,2026-01-05,2026-01-06,2026-01-07,2026-01-08,2026-01-09,2026-01-10
A,0.738467,-1.478522,0.343618,-0.676922,-0.839218,-0.479174,0.812526,0.361636,-0.035826,0.087047
B,0.171368,-0.719844,-1.763040,0.611676,-0.309212,-0.185659,1.356240,-0.645120,1.564644,-0.299007
C,-0.115648,-0.460639,0.324084,1.031000,0.331263,-1.106335,-0.072010,0.361396,-2.619745,0.091761
D,-0.301104,1.057122,-0.385082,0.931280,0.975545,-1.196207,1.003533,1.538037,0.821903,-1.987569

In [43]:
df.describe().transpose()

   count      mean       std       min       25%       50%       75%       max
A   10.0 -0.116637  0.738267 -1.478522 -0.627485  0.025611  0.357132  0.812526
B   10.0 -0.021795  0.997130 -1.763040 -0.561143 -0.242333  0.501599  1.564644
C   10.0 -0.223487  1.012976 -2.619745 -0.374391  0.009875  0.329469  1.031000
D   10.0  0.245746  1.154750 -1.987569 -0.364088  0.876591  0.996536  1.538037

Sorting by an axis:

In [44]:
df.sort_index(axis=0, ascending=False) # axis=1 Columns (0,1) == (Row, Column)

                   A         B         C         D
2026-01-10  0.087047 -0.299007  0.091761 -1.987569
2026-01-09 -0.035826  1.564644 -2.619745  0.821903
2026-01-08  0.361636 -0.645120  0.361396  1.538037
2026-01-07  0.812526  1.356240 -0.072010  1.003533
2026-01-06 -0.479174 -0.185659 -1.106335 -1.196207
2026-01-05 -0.839218 -0.309212  0.331263  0.975545
2026-01-04 -0.676922  0.611676  1.031000  0.931280
2026-01-03  0.343618 -1.763040  0.324084 -0.385082
2026-01-02 -1.478522 -0.719844 -0.460639  1.057122
2026-01-01  0.738467  0.171368 -0.115648 -0.301104

Sorting by values:

In [46]:
df.sort_values(by='B', ascending=True)

                   A         B         C         D
2026-01-03  0.343618 -1.763040  0.324084 -0.385082
2026-01-02 -1.478522 -0.719844 -0.460639  1.057122
2026-01-08  0.361636 -0.645120  0.361396  1.538037
2026-01-05 -0.839218 -0.309212  0.331263  0.975545
2026-01-10  0.087047 -0.299007  0.091761 -1.987569
2026-01-06 -0.479174 -0.185659 -1.106335 -1.196207
2026-01-01  0.738467  0.171368 -0.115648 -0.301104
2026-01-04 -0.676922  0.611676  1.031000  0.931280
2026-01-07  0.812526  1.356240 -0.072010  1.003533
2026-01-09 -0.035826  1.564644 -2.619745  0.821903

#### Selection

Selecting a single column yields a `Series`.

In [47]:
df['A']

2026-01-01    0.738467
2026-01-02   -1.478522
2026-01-03    0.343618
2026-01-04   -0.676922
2026-01-05   -0.839218
2026-01-06   -0.479174
2026-01-07    0.812526
2026-01-08    0.361636
2026-01-09   -0.035826
2026-01-10    0.087047
Freq: D, Name: A, dtype: float64

Selecting with `[]` slices the rows

In [48]:
df[0:3]

                   A         B         C         D
2026-01-01  0.738467  0.171368 -0.115648 -0.301104
2026-01-02 -1.478522 -0.719844 -0.460639  1.057122
2026-01-03  0.343618 -1.763040  0.324084 -0.385082

In [49]:
df['20260101':'20260105']

                   A         B         C         D
2026-01-01  0.738467  0.171368 -0.115648 -0.301104
2026-01-02 -1.478522 -0.719844 -0.460639  1.057122
2026-01-03  0.343618 -1.763040  0.324084 -0.385082
2026-01-04 -0.676922  0.611676  1.031000  0.931280
2026-01-05 -0.839218 -0.309212  0.331263  0.975545

### DataFrames

#### Introduction

A dataframe is a two dimensional data structure, i.e. data ia aligned in a tabular fashion in rows and columns. Pandas DataFrames consists of three principal components, the data, rows and columns.

We will get a brief insight on all these basic operation which can be performed on Pandas DataFrame:

1. Creating a DataFrame
2. Dealing with Rows and Columns
3. Indexing and Selecting Data
4. Working with Missing Data
5. Iterating over rows and columns

In the real world, a Pandas DataFrame will be created by loading the datasets from existing storage, storage can be SQL Database, CSV file and Excel file. Pandas DataFrame can be created form the lists, dictionary, and from a list of dictionary etc. DataFrame can be created in different ways. Here are some ways by which we create a dataframe:

#### Creating a dataframe using a List:

DataFrame can be created using a single list or a list of lists.

In [50]:
import pandas as pd

Creating a list of strings.

In [51]:
state_list = ['California', 'Texas', 'New York', 'Florida', 'Illinois']

Call the DataFrame constructor on the list.

In [52]:
df = pd.DataFrame(state_list)

In [53]:
df

            0
0  California
1       Texas
2    New York
3     Florida
4    Illinois

#### Creating DataFrame from dict of ndarray/lists:

To create DataFrame from dict of ndarray/list, all the arrays must be same length. If index is passed then the length index should be equal to the length of arrays. If no index is passed, then, by default, index will be range(n) where n is the array length.

Initialize dictionary of lists.

In [54]:
data = {
    'state': ['California', 'Texas', 'New York', 'Florida', 'Illinois'],
    'pop': [3833252, 26448193, 19651127, 19552860, 12882135],
    'area': [423967, 695662, 141297, 170312, 149995]
}

In [55]:
df = pd.DataFrame(data)

In [56]:
df.set_index(keys='state', inplace=True)

In [57]:
df

                 pop    area
state
California   3833252  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995

#### Dealing with Rows and Columns

A DataFrame is a two dimensional data structure i.e. data is aligned in a tabular fashion in rows and columns. We can peform basic operations on rows/columns like selecting, deleting, adding and renaming.

#### Column Selection:

The individual Series that make up the columns of the DataFrame can be accessed via dictionary style indexing of the column name:

In [58]:
df['area']

state
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Equivalently, we can use attribute-style access with column names that are strings:

In [59]:
df.area

state
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Though this is a useful shorthand, keep in mind that it does not work for all cases! For example, if the column names are not the strings, or if the column names conflict with methods of the DataFrame, this attribute-style access is not possible. For example, the DataFrame has a `pop()` method so `data.pop` will point to this rather than the "pop" column.

In [65]:
df.area

state
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [64]:
df.area is df['area']

True

In particular, you should avoid the temptation to try column assignment via attribute (i.e use `data['pop'] = z` rather than `data.pop=z`).

Like with the Series objects discussed earlier, this dictionary style syntax can also be used to modify the object, in this case adding a new column:

In [61]:
df['density'] = df['pop'] / df['area']

In [62]:
df

                 pop    area     density
state
California   3833252  423967    9.041392
Texas       26448193  695662   38.018740
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

#### Select Multiple Columns

In [66]:
df[['density', 'area']]

               density    area
state
California    9.041392  423967
Texas        38.018740  695662
New York    139.076746  141297
Florida     114.806121  170312
Illinois     85.883763  149995

In [69]:
my_cols = ['area', 'pop']
df[my_cols]

              area       pop
state
California  423967   3833252
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

#### Row Selection:

Pandas provide a unique method to retrieve rows from a Data Frame. `DataFrame.loc[]` method is used to retrieve rows from Pandas DataFrame. Rows can also be selected by passing integer location to an `iloc[]` function.

In [67]:
df.loc['California'] # Notice the brackets !!!

pop        3.833252e+06
area       4.239670e+05
density    9.041392e+00
Name: California, dtype: float64

In [70]:
df.loc['Texas']

pop        2.644819e+07
area       6.956620e+05
density    3.801874e+01
Name: Texas, dtype: float64

#### Indexing and Selecting Data

Indexing in pandas means simply selecting particular rows and columns of data from a DataFrame. Indexing could mean selecting all the rows and some of the columns, some of the rows and all of the columns, or some of each of the rows and columns. Indexing can also be known as Subset Selection.

##### Indexing a DataFrame using indexing operator:

Indexing operator is used to refer to the square brackets follwing an object. The `.loc` and `.iloc` indexers also use the indexing operator to make selections. In this indexing operator to refer to `df[]`.

#### Selecting Single Columns

In order to select a single column, we simply put the name of the column in between the brackets.

In [71]:
df['density']

state
California      9.041392
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.883763
Name: density, dtype: float64

#### Selecting Multiple Columns

In [72]:
df[['area', 'density']]

              area     density
state
California  423967    9.041392
Texas       695662   38.018740
New York    141297  139.076746
Florida     170312  114.806121
Illinois    149995   85.883763

#### Indexing a DataFrame using .iloc[]:

This function selects data by the label of rows and columns. The df.loc indexer selects data in a different way than just the indexing operator. It can select subsets of rows or columns. It can also simultaneously select subsets of rows and columns.

#### Selecting a single row

In order to select a single row using .loc[], we put a single row label in a .loc function.

In [74]:
df.loc['Florida']

pop        1.955286e+07
area       1.703120e+05
density    1.148061e+02
Name: Florida, dtype: float64

#### Selecting multiple rows

In [75]:
df.loc[['Florida', 'Illinois']] # Use list object for multiple rows

               pop    area     density
state
Florida   19552860  170312  114.806121
Illinois  12882135  149995   85.883763

#### Indexing a DataFrame using .iloc[]:

This function allows us to retrieve rows and columns by position. In order to do that, we will need to specify the positions of the rows that we want, and the positions of the columns that we want as well. The df.iloc indexer is very similar to df.loc but only uses integer locations to make its selections.

#### Selecting a single row

In order to select a single row using `.iloc[]`, we can pass a single integer to `.iloc[]` function.

In [76]:
df.iloc[2]

pop        1.965113e+07
area       1.412970e+05
density    1.390767e+02
Name: New York, dtype: float64

#### Selecting multiple rows

In [77]:
df.iloc[[0,2]]

                 pop    area     density
state
California   3833252  423967    9.041392
New York    19651127  141297  139.076746