## Pandas Basics 

### Understanding Joins/Mergers

The colored column represents the 'key' variable: these are used to match the rows between the tables. The grey column represents the 'value' column that is carried along for the ride. In these examples, I will show a single key variable, but the idea generalizes in a straightforward way to multiple keys and multiple values.

A join is a way of connecting each row in `x` to zero, or more rows in `y`. The following diagram shows each potential match as an intersection of a pair of lines.

(If you look closely, you might notice that we have switched the order of the key and value columns in x). This is to emphasize that joins match based on the key, the value is just carried along for the ride.)

#### Inner Join

The simplest type of join is the inner join. An inner join matches the pair of observations whenever their keys are equal.

The most important property of an inner join is that unmatched rows are not included in the result. This means that generally inner joins are usually not appropriate for use in analysis because it's too easy to lose observations.

#### Outer Joins

An inner join keeps observations that appear in both tables. An outer join keeps observations that appear in at least one of the tables. There are three types of outer joins:

* A left join keeps all observations in x.
* A right join keeps all observations in y.
* A full join keeps all observations in x and y.

These joins work by adding an additional "virtual" observation to each table. This observations has a key that always matches (if no other key matches), and a value filled with NA.

The most commonly used join is the left join: you use this whenever you look up additional data from another table, because it preserves the original observations even when there is not a match.

Another way to depict the different types of joins is with a Venn diagram:

#### Duplicate Keys

So far all the diagram have assumed that the keys are unique. But that's not always the case. This section explains what happens when the keys are not unique. There are two possibilities:

1. One table has duplicate keys. This is useful when you want to add in additional information as there is typically a one-to-many relationship.

2. Both tables have duplicate keys. This is usually an error because in neither table do the keys uniquely identify an observation. When you join duplicated keys, you get all possible combinations, the Cartesian product.

#### Defining the key columns

So far, the pair of tables have always been joined by a single variable, and that variable has the same name in both tables. That constraint was encoded by `on="key"`. You can use other values for by to connect the tables in other ways:

### Merge

#### Concat

pandas provides various facilities for easily combining together Series and DataFrame objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join/merge type operations.

Concatenating pandas objects together with `concat()`:

In [1]:
import pandas as pd
import numpy as np
np.random.seed(42)
df = pd.DataFrame(np.random.randn(10,4))

In [2]:
df # DataFrame

          0         1         2         3
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304
5  1.465649 -0.225776  0.067528 -1.424748
6 -0.544383  0.110923 -1.150994  0.375698
7 -0.600639 -0.291694 -0.601707  1.852278
8 -0.013497 -1.057711  0.822545 -1.220844
9  0.208864 -1.959670 -1.328186  0.196861

In [3]:
df[:3]

          0         1         2         3
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730

In [4]:
pieces = [df[:3], df[3:7], df[7:]] # break it into pieces

In [5]:
pieces

[          0         1         2         3
 0  0.496714 -0.138264  0.647689  1.523030
 1 -0.234153 -0.234137  1.579213  0.767435
 2 -0.469474  0.542560 -0.463418 -0.465730,
           0         1         2         3
 3  0.241962 -1.913280 -1.724918 -0.562288
 4 -1.012831  0.314247 -0.908024 -1.412304
 5  1.465649 -0.225776  0.067528 -1.424748
 6 -0.544383  0.110923 -1.150994  0.375698,
           0         1         2         3
 7 -0.600639 -0.291694 -0.601707  1.852278
 8 -0.013497 -1.057711  0.822545 -1.220844
 9  0.208864 -1.959670 -1.328186  0.196861]

In [6]:
pd.concat(pieces)

          0         1         2         3
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304
5  1.465649 -0.225776  0.067528 -1.424748
6 -0.544383  0.110923 -1.150994  0.375698
7 -0.600639 -0.291694 -0.601707  1.852278
8 -0.013497 -1.057711  0.822545 -1.220844
9  0.208864 -1.959670 -1.328186  0.196861

### Join

SQL style merges.

In [7]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1,2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4,5]})

In [8]:
left

   key  lval
0  foo     1
1  foo     2

In [9]:
right

   key  rval
0  foo     4
1  foo     5

In [10]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

#### Another key

In [11]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1,2]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4,5]})

In [12]:
left

   key  lval
0  foo     1
1  bar     2

In [13]:
right

   key  rval
0  foo     4
1  bar     5

In [14]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  bar     2     5

### Append

Append rows to a dataframe.

In [15]:
df = pd.DataFrame(np.random.randn(8,4), columns=['A', 'B', 'C', 'D'])

In [16]:
df

          A         B         C         D
0  0.738467  0.171368 -0.115648 -0.301104
1 -1.478522 -0.719844 -0.460639  1.057122
2  0.343618 -1.763040  0.324084 -0.385082
3 -0.676922  0.611676  1.031000  0.931280
4 -0.839218 -0.309212  0.331263  0.975545
5 -0.479174 -0.185659 -1.106335 -1.196207
6  0.812526  1.356240 -0.072010  1.003533
7  0.361636 -0.645120  0.361396  1.538037

In [17]:
s = df.iloc[3]

In [25]:
s.to_frame().T

          A         B      C        D
3 -0.676922  0.611676  1.031  0.93128

In [28]:
pd.concat([df, s.to_frame().T], ignore_index=True)

          A         B         C         D
0  0.738467  0.171368 -0.115648 -0.301104
1 -1.478522 -0.719844 -0.460639  1.057122
2  0.343618 -1.763040  0.324084 -0.385082
3 -0.676922  0.611676  1.031000  0.931280
4 -0.839218 -0.309212  0.331263  0.975545
5 -0.479174 -0.185659 -1.106335 -1.196207
6  0.812526  1.356240 -0.072010  1.003533
7  0.361636 -0.645120  0.361396  1.538037
8 -0.676922  0.611676  1.031000  0.931280

### Merging, Joining, and Concatenating

There are 3 methods to combine DataFrames:

1. Merging (`pd.merge()`)
2. Joining (`df_left.join(df_right)`)
3. Concatenating (`pd.concat()`)

### Create DataFrame Examples using List Comprehension

**List comprehension** offers a shorter syntax when you want to create a new list based on the values of an existing list.

Example:

Based on a list of fruits, you want a new list, containing only the fruits with the letter "a" in the name.

Without list comprehension you will have to write a for statement with a condition test inside:

In [29]:
fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango']
newlist = []

for x in fruits:
    if "a" in x:
        newlist.append(x)

print(newlist)

['apple', 'banana', 'mango']

With list comprehension you can do all that with only one line of code:

In [30]:
fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango']

newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']

In [31]:
import numpy as np
import pandas as pd

In [32]:
l = [let + str(num) for let in ['A', 'B', 'C', 'D'] for num in range(12)]

In [33]:
l

['A0',
 'A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'A9',
 'A10',
 'A11',
 'B0',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'B6',
 'B7',
 'B8',
 'B9',
 'B10',
 'B11',
 'C0',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'D0',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'D10',
 'D11']

In [34]:
n = 4
d = [l[i:i + n] for i in range(0, len(l), n)]

In [47]:
d

[['A0', 'A1', 'A2', 'A3'],
 ['A4', 'A5', 'A6', 'A7'],
 ['A8', 'A9', 'A10', 'A11'],
 ['B0', 'B1', 'B2', 'B3'],
 ['B4', 'B5', 'B6', 'B7'],
 ['B8', 'B9', 'B10', 'B11'],
 ['C0', 'C1', 'C2', 'C3'],
 ['C4', 'C5', 'C6', 'C7'],
 ['C8', 'C9', 'C10', 'C11'],
 ['D0', 'D1', 'D2', 'D3'],
 ['D4', 'D5', 'D6', 'D7'],
 ['D8', 'D9', 'D10', 'D11']]

In [35]:
df_1 = pd.DataFrame({'A': d[0], 'B': d[3],
                    'C': d[6], 'D': d[9]},
                   index=[0,1,2,3])

df_2 = pd.DataFrame({'A': d[1], 'B': d[4],
                    'C': d[7], 'D': d[10]},
                   index=[4,5,6,7])

df_3 = pd.DataFrame({'A': d[2], 'B': d[5],
                    'C': d[8], 'D': d[11]},
                   index=[8,9,10,11])

In [36]:
df_1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [37]:
df_2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [38]:
df_3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

### Concatenation

* Concatenation glues together DataFrames
* The dimensions of each series should match
* Use `pd.concat()` with list of DataFrames

In [40]:
pd.concat([df_1, df_2, df_3], axis=0)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [41]:
pd.concat([df_1, df_2, df_3], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

#### Example DataFrames with Keys

In [42]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': d[0],
                    'B': d[3]})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'C': d[6],
                     'D': d[9]})

In [43]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [44]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

#### Merging

* `pd.merge()` allows you to merge DataFrames together
* This is similar to merging SQL tables

In [45]:
pd.merge(left, right, how='inner', on="key")

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

Or to show a more complicated example:

In [49]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K1'],
                    'A': d[0],
                    'B': d[3]})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                     'key2': ['K0', 'K0', 'K0', 'K0'],
                     'C': d[6],
                     'D': d[9]})

In [50]:
pd.merge(left, right,how='inner', on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [51]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [52]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [53]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

#### Joining

* `left.join(right)` combines the columns of two (potentially differently) indexed DataFrames into a single DataFrame.

In [54]:
left = pd.DataFrame({
    'A': d[0],
    'B': d[3]},
    index=['K0', 'K1', 'K2', 'K4'])

right = pd.DataFrame({
    'C': d[6],
    'D': d[9]
}, index=['K0', 'K2', 'K3', 'K5'])

In [57]:
left

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
K4  A3  B3

In [58]:
right

     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2
K5  C3  D3

In [55]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1
K4  A3  B3  NaN  NaN

In [56]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2
K4   A3   B3  NaN  NaN
K5  NaN  NaN   C3   D3