## Reshaping and Pivoting DataFrames with Pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    'date': ['2000-01-03', '2000-01-04', '2000-01-05', '2000-01-03', '2000-01-04', 
    '2000-01-05', '2000-01-03', '2000-01-04', '2000-01-05', '2000-01-03', '2000-01-04', '2000-01-05'],
    'variable': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'D', 'D', 'D'],
    'value': [0.794309, 0.427748, -1.544155, 0.128190, -0.351577, 0.839166, -0.563507, 0.744192, 0.016040, 0.287683, 0.224715, -0.583553]
})

In [4]:
df

          date variable     value
0   2000-01-03        A  0.794309
1   2000-01-04        A  0.427748
2   2000-01-05        A -1.544155
3   2000-01-03        B  0.128190
4   2000-01-04        B -0.351577
5   2000-01-05        B  0.839166
6   2000-01-03        C -0.563507
7   2000-01-04        C  0.744192
8   2000-01-05        C  0.016040
9   2000-01-03        D  0.287683
10  2000-01-04        D  0.224715
11  2000-01-05        D -0.583553

In [5]:
df[df['variable']=='B']

         date variable     value
3  2000-01-03        B  0.128190
4  2000-01-04        B -0.351577
5  2000-01-05        B  0.839166

In [6]:
df.pivot(index='date', columns='variable', values='value')

variable           A         B         C         D
date
2000-01-03  0.794309  0.128190 -0.563507  0.287683
2000-01-04  0.427748 -0.351577  0.744192  0.224715
2000-01-05 -1.544155  0.839166  0.016040 -0.583553

In [7]:
df['value_2'] = df['value']*2

In [8]:
df

          date variable     value   value_2
0   2000-01-03        A  0.794309  1.588618
1   2000-01-04        A  0.427748  0.855496
2   2000-01-05        A -1.544155 -3.088310
3   2000-01-03        B  0.128190  0.256380
4   2000-01-04        B -0.351577 -0.703154
5   2000-01-05        B  0.839166  1.678332
6   2000-01-03        C -0.563507 -1.127014
7   2000-01-04        C  0.744192  1.488384
8   2000-01-05        C  0.016040  0.032080
9   2000-01-03        D  0.287683  0.575366
10  2000-01-04        D  0.224715  0.449430
11  2000-01-05        D -0.583553 -1.167106

In [14]:
df_pivot_vals = df.pivot(index='date', columns='variable')

In [15]:
df_pivot_vals

               value                                 value_2            \
variable           A         B         C         D         A         B
date
2000-01-03  0.794309  0.128190 -0.563507  0.287683  1.588618  0.256380
2000-01-04  0.427748 -0.351577  0.744192  0.224715  0.855496 -0.703154
2000-01-05 -1.544155  0.839166  0.016040 -0.583553 -3.088310  1.678332


variable           C         D
date
2000-01-03 -1.127014  0.575366
2000-01-04  1.488384  0.449430
2000-01-05  0.032080 -1.167106

In [17]:
df_pivot_vals['value_2']

variable           A         B         C         D
date
2000-01-03  1.588618  0.256380 -1.127014  0.575366
2000-01-04  0.855496 -0.703154  1.488384  0.449430
2000-01-05 -3.088310  1.678332  0.032080 -1.167106

#### Reshaping by stacking and unstacking

* **stack**: "pivot" a level of the column labels, returning a DataFrame with an index with a new inner most level of row labels.
* **unstack**: (inverse operation of stack) "pivot" a level of the row index to the column axis, producing a reshaped DataFrame with a new innet most level of column labels.

In [18]:
df

          date variable     value   value_2
0   2000-01-03        A  0.794309  1.588618
1   2000-01-04        A  0.427748  0.855496
2   2000-01-05        A -1.544155 -3.088310
3   2000-01-03        B  0.128190  0.256380
4   2000-01-04        B -0.351577 -0.703154
5   2000-01-05        B  0.839166  1.678332
6   2000-01-03        C -0.563507 -1.127014
7   2000-01-04        C  0.744192  1.488384
8   2000-01-05        C  0.016040  0.032080
9   2000-01-03        D  0.287683  0.575366
10  2000-01-04        D  0.224715  0.449430
11  2000-01-05        D -0.583553 -1.167106

In [24]:
df2 = pd.DataFrame(
    data = {
        'A': [-0.594045, 0.812831, -1.492472, 0.422326],
        'B': [0.989808, 0.744916, -0.668162, -0.545292]    
    }
)

In [25]:
df2

          A         B
0 -0.594045  0.989808
1  0.812831  0.744916
2 -1.492472 -0.668162
3  0.422326 -0.545292

In [29]:
df2.index = pd.MultiIndex.from_product([['bar', 'baz'], ['one', 'two']], names=['first', 'second'])

In [30]:
df2

                     A         B
first second
bar   one    -0.594045  0.989808
      two     0.812831  0.744916
baz   one    -1.492472 -0.668162
      two     0.422326 -0.545292

In [33]:
stacked = df2.stack()

In [34]:
stacked

first  second
bar    one     A   -0.594045
               B    0.989808
       two     A    0.812831
               B    0.744916
baz    one     A   -1.492472
               B   -0.668162
       two     A    0.422326
               B   -0.545292
dtype: float64

In [41]:
stacked.unstack(2)

                     A         B
first second
bar   one    -0.594045  0.989808
      two     0.812831  0.744916
baz   one    -1.492472 -0.668162
      two     0.422326 -0.545292

In [36]:
stacked.unstack(1)

second        one       two
first
bar   A -0.594045  0.812831
      B  0.989808  0.744916
baz   A -1.492472  0.422326
      B -0.668162 -0.545292

In [37]:
stacked.unstack(0)

first          bar       baz
second
one    A -0.594045 -1.492472
       B  0.989808 -0.668162
two    A  0.812831  0.422326
       B  0.744916 -0.545292

In [38]:
stacked.unstack('second')

second        one       two
first
bar   A -0.594045  0.812831
      B  0.989808  0.744916
baz   A -1.492472  0.422326
      B -0.668162 -0.545292

In [43]:
df3 = pd.DataFrame([[0.160287, 1.015534, 1.030470, 0.508472],
                  [1.368757, -1.447397, -0.246379, 0.153493],
                  [1.230501, -2.224046, 1.341282, 0.186118],
                  [-0.082465, -1.045151, 0.432698, -0.063779]])

In [45]:
df3

          0         1         2         3
0  0.160287  1.015534  1.030470  0.508472
1  1.368757 -1.447397 -0.246379  0.153493
2  1.230501 -2.224046  1.341282  0.186118
3 -0.082465 -1.045151  0.432698 -0.063779

In [49]:
df3.columns = pd.MultiIndex.from_arrays([
    ['A', 'B', 'A', 'B'],
    ['cat', 'cat', 'dog', 'dog'],
    ['long', 'long', 'short', 'short']],
    names=['exp', 'animal', 'hair_length']
)

In [50]:
df3

exp                 A         B         A         B
animal            cat       cat       dog       dog
hair_length      long      long     short     short
0            0.160287  1.015534  1.030470  0.508472
1            1.368757 -1.447397 -0.246379  0.153493
2            1.230501 -2.224046  1.341282  0.186118
3           -0.082465 -1.045151  0.432698 -0.063779

In [52]:
df3.stack(level=['animal', 'hair_length']) # string index / named index

/tmp/ipykernel_6287/669388637.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df3.stack(level=['animal', 'hair_length'])

exp                          A         B
  animal hair_length
0 cat    long         0.160287  1.015534
  dog    short        1.030470  0.508472
1 cat    long         1.368757 -1.447397
  dog    short       -0.246379  0.153493
2 cat    long         1.230501 -2.224046
  dog    short        1.341282  0.186118
3 cat    long        -0.082465 -1.045151
  dog    short        0.432698 -0.063779

In [53]:
df3.stack(level=[1,2]) # numeric index

/tmp/ipykernel_6287/1665287481.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df3.stack(level=[1,2])

exp                          A         B
  animal hair_length
0 cat    long         0.160287  1.015534
  dog    short        1.030470  0.508472
1 cat    long         1.368757 -1.447397
  dog    short       -0.246379  0.153493
2 cat    long         1.230501 -2.224046
  dog    short        1.341282  0.186118
3 cat    long        -0.082465 -1.045151
  dog    short        0.432698 -0.063779

#### Melt

In [54]:
cheese = pd.DataFrame(
    {
        'first': ['John', 'Mary'],
        'last': ['Doe', 'Bo'],
        'height': [5.5, 6.0],
        'weight': [130, 150]
    }
)

In [55]:
cheese

  first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

In [56]:
cheese.melt(id_vars=['first', 'last'])

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [58]:
cheese.melt(id_vars=['first', 'last'], var_name='quant', value_name='metrics')

  first last   quant  metrics
0  John  Doe  height      5.5
1  Mary   Bo  height      6.0
2  John  Doe  weight    130.0
3  Mary   Bo  weight    150.0